function [fitresult, gof] = psat_fit(pwr_x, cps_Y)
%CREATEFIT(PWR_X,DIFF_Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: pwr_x
%      Y Output: diff_Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Apr-2023 00:03:21


%% Fit:
[xData, yData] = prepareCurveData( pwr_x, cps_Y );

% Set up fittype and options.
ft = fittype( '(a*P/(P+b)) + (c*P)', 'independent', 'P', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0];
opts.StartPoint = [0.8 600 0.05266];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );